install:
  - choco install ant
  - ps: Start-FileDownload 'http://www-us.apache.org/dist//ant/ivy/2.4.0/apache-ivy-2.4.0-bin.zip'
  - 7z x apache-ivy-2.4.0-bin.zip
  - cd apache-ivy-2.4.0
  - mkdir C:\Users\appveyor\.ant\lib
  - copy ivy-2.4.0.jar C:\Users\appveyor\.ant\lib
  - cd ..
  - SET PATH=C:\Ruby22\bin;%PATH%
  - ps: refreshenv
  - gem install os
  - ruby --version
  - rake --version
  - java -version
  - ant -version

before_test:
  - rake dependencies
  - rake

test_script:
  - rake test

build: off
