install:
  - choco install ant
  - gem install os
  - ruby --version
  - rake --version
  - java -version
  - ant -version

before_test:
  - rake

test_script:
  - rake test
  - rake unittest

build: off
